apiVersion: v1
kind: Service
metadata:
  name: newsfeed-service
spec:
  selector:
    app: newsfeed-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80        # Cluster IP port
      targetPort: 80  # Container port
      nodePort: 30007 # Host-accessible port (Minikube)
